version: '3.3'
services:
  app:
    build:
      dockerfile: Dockerfile        
    image: gamefutbol:latest
    ports:
      - "3000:3001"
    environment:
      DB_USER: root
      DB_PASS: Zafiro30
      DB_NAME: dataGame
      DB_HOST: mysql
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: ''
      SECRET_PASSPHRASE: SCM123LA0VE34A4JUBEA34

    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  mysql:
    image: mysql:8.0.36
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Zafiro30
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dataGame
    ports:
      - "3307:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
    shm_size: 512m
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10


  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    command: ["redis-server", "--appendonly", "yes"]
    shm_size: 512m 
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 20s
      retries: 10
    
