name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/gamefutbol:latest

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build-and-push
#     steps:
#     - name: Deploy to server
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USER }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         script: |
#           docker pull ghcr.io/${{ github.repository_owner }}/iscraper:latest
#           docker stop myapp || true
#           docker rm myapp || true
#           docker run -d --name myapp -p 80:80 ghcr.io/${{ github.repository_owner }}/iscraper:latest
